<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (GVK_ID?,STRUCTURE_ID?,VAL_SMILES?,ORAL?,CNS?,ORAL_CHEM_PC1?,ORAL_CHEM_PC2?,ORAL_CHEM_PC3?,ORAL_PHYSPROP_PC1?,ORAL_PHYSPROP_PC2?,ORAL_PHYSPROP_PC3?,CNS_CHEM_PC1?,CNS_CHEM_PC2?,CNS_CHEM_PC3?,CNS_PHYSPROP_PC1?,CNS_PHYSPROP_PC2?,CNS_PHYSPROP_PC3?,ALL_CHEM_PC1?,ALL_CHEM_PC2?,ALL_CHEM_PC3?,ALL_PHYSPROP_PC1?,ALL_PHYSPROP_PC2?,ALL_PHYSPROP_PC3?,MOLECULAR_WEIGHT?,CLOGP?,LOGD_PH7_4?,HBOND_ACCEPTOR?,HBOND_DONOR_HYDROGEN?,ROTATABLE_BONDS?,CMR?,MOLECULAR_SOLUBILITY?,NUM_ATOMS?,TPSA?,HALOGEN_COUNT?,NITROGEN_OXYGEN_COUNT?,CREATED_USER?,CREATED_DATE?,MODIFIED_USER?,MODIFIED_DATE?,TARGET?)+>
  <!ELEMENT GVK_ID (#PCDATA)>
  <!ELEMENT STRUCTURE_ID (#PCDATA)>
  <!ELEMENT VAL_SMILES (#PCDATA)>
  <!ELEMENT ORAL (#PCDATA)>
  <!ELEMENT CNS (#PCDATA)>
  <!ELEMENT ORAL_CHEM_PC1 (#PCDATA)>
  <!ELEMENT ORAL_CHEM_PC2 (#PCDATA)>
  <!ELEMENT ORAL_CHEM_PC3 (#PCDATA)>
  <!ELEMENT ORAL_PHYSPROP_PC1 (#PCDATA)>
  <!ELEMENT ORAL_PHYSPROP_PC2 (#PCDATA)>
  <!ELEMENT ORAL_PHYSPROP_PC3 (#PCDATA)>
  <!ELEMENT CNS_CHEM_PC1 (#PCDATA)>
  <!ELEMENT CNS_CHEM_PC2 (#PCDATA)>
  <!ELEMENT CNS_CHEM_PC3 (#PCDATA)>
  <!ELEMENT CNS_PHYSPROP_PC1 (#PCDATA)>
  <!ELEMENT CNS_PHYSPROP_PC2 (#PCDATA)>
  <!ELEMENT CNS_PHYSPROP_PC3 (#PCDATA)>
  <!ELEMENT ALL_CHEM_PC1 (#PCDATA)>
  <!ELEMENT ALL_CHEM_PC2 (#PCDATA)>
  <!ELEMENT ALL_CHEM_PC3 (#PCDATA)>
  <!ELEMENT ALL_PHYSPROP_PC1 (#PCDATA)>
  <!ELEMENT ALL_PHYSPROP_PC2 (#PCDATA)>
  <!ELEMENT ALL_PHYSPROP_PC3 (#PCDATA)>
  <!ELEMENT MOLECULAR_WEIGHT (#PCDATA)>
  <!ELEMENT CLOGP (#PCDATA)>
  <!ELEMENT LOGD_PH7_4 (#PCDATA)>
  <!ELEMENT HBOND_ACCEPTOR (#PCDATA)>
  <!ELEMENT HBOND_DONOR_HYDROGEN (#PCDATA)>
  <!ELEMENT ROTATABLE_BONDS (#PCDATA)>
  <!ELEMENT CMR (#PCDATA)>
  <!ELEMENT MOLECULAR_SOLUBILITY (#PCDATA)>
  <!ELEMENT NUM_ATOMS (#PCDATA)>
  <!ELEMENT TPSA (#PCDATA)>
  <!ELEMENT HALOGEN_COUNT (#PCDATA)>
  <!ELEMENT NITROGEN_OXYGEN_COUNT (#PCDATA)>
  <!ELEMENT CREATED_USER (#PCDATA)>
  <!ELEMENT CREATED_DATE (#PCDATA)>
  <!ELEMENT MODIFIED_USER (#PCDATA)>
  <!ELEMENT MODIFIED_DATE (#PCDATA)>
  <!ELEMENT TARGET (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TARGET>Gonadotropin-releasing hormone receptor</TARGET>
    <GVK_ID>GONADORELIN HYDROCHLORIDE / 5900560</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>CC(C)C[C@H](NC(=O)CNC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@H](CO)NC(=O)[C@H](Cc2c[nH]c3ccccc23)NC(=O)[C@H](Cc4cnc[nH]4)NC(=O)C5CCC(=O)N5)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N6CCC[C@@H]6C(=O)NCC(=O)N</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-3.48939194640682</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>8.47987844677384</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-4.53415614483399</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>12.409560376369</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-.804287657334096</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>-.122781167458489</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-3.2428380152902174</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>17.850961404938548</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>2.8192326292892127</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>11.768311890739678</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-.73367580812582722</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>-.1383627731995298</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>1182.2901000000002</MOLECULAR_WEIGHT>
    <CLOGP>-3.851</CLOGP>
    <LOGD_PH7_4>-3.491</LOGD_PH7_4>
    <HBOND_ACCEPTOR>15</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>17</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>32</ROTATABLE_BONDS>
    <CMR>301.654</CMR>
    <MOLECULAR_SOLUBILITY>-8.5640000000000001</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>85</NUM_ATOMS>
    <TPSA>472.12</TPSA>
    <HALOGEN_COUNT>0</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>30</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Dopamine receptor D2</TARGET>
    <GVK_ID>TRIFLUPERIDOL / 5902481</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>OC1(CCN(CCCC(=O)c2ccc(F)cc2)CC1)c3cccc(c3)C(F)(F)F</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-.252008114281065</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>-.0624626116392257</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>.815363241373623</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-.356596776963617</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>2.18417803723324</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>3.17454068884181</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>.16316927159222089</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>-1.4966056427546781</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>1.6460382551421615</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-.30559614096188559</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>2.2076176774998841</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>3.3336113092143407</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>409.41713000000004</MOLECULAR_WEIGHT>
    <CLOGP>4.165</CLOGP>
    <LOGD_PH7_4>3.353</LOGD_PH7_4>
    <HBOND_ACCEPTOR>3</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>1</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>7</ROTATABLE_BONDS>
    <CMR>103.76000000000001</CMR>
    <MOLECULAR_SOLUBILITY>-5.9960000000000004</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>29</NUM_ATOMS>
    <TPSA>40.539999999999999</TPSA>
    <HALOGEN_COUNT>4</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>3</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Luteinizing hormone-releasing hormone</TARGET>
    <GVK_ID>GOSERELIN ACETATE / 5900562</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>CC(C)C[C@H](NC(=O)[C@H](COC(C)(C)C)NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@H](CO)NC(=O)[C@H](Cc2c[nH]c3ccccc23)NC(=O)[C@H](Cc4cnc[nH]4)NC(=O)C5CCC(=O)N5)C(=O)N[C@@H](CCCNC(=N)N)C(=O)N6CCC[C@H]6C(=O)NNC(=O)N</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-3.56254915603579</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>8.41948302580331</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-3.34467205464913</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>13.3800056800953</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-.0530275159642808</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>-.251800118731455</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-3.2534381339872609</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>17.3906396023498</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>2.8049799823115884</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>12.665979200353192</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>.014976084092009345</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>-.27437108875401223</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>1269.4104600000001</MOLECULAR_WEIGHT>
    <CLOGP>-2.8100000000000001</CLOGP>
    <LOGD_PH7_4>-2.45</LOGD_PH7_4>
    <HBOND_ACCEPTOR>16</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>18</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>34</ROTATABLE_BONDS>
    <CMR>324.98599999999999</CMR>
    <MOLECULAR_SOLUBILITY>-9.843</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>91</NUM_ATOMS>
    <TPSA>493.38</TPSA>
    <HALOGEN_COUNT>0</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>32</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>5-Hydroxytryptamine 3 receptor</TARGET>
    <GVK_ID>GRANISETRON HYDROCHLORIDE / 5900564</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>CN1C2CCCC1CC(C2)NC(=O)c3nn(C)c4ccccc34</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-.266494755734826</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>.0821023912594995</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-1.10728369615645</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-.765974720209329</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-.214883807852198</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>-.43328228200079</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-.36525912472626387</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>.80689854889062607</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>2.1244256313807184</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-.65338236655350979</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-.19424313438313889</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>-.4352020397791837</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>312.40935000000002</MOLECULAR_WEIGHT>
    <CLOGP>2.4010000000000002</CLOGP>
    <LOGD_PH7_4>.84</LOGD_PH7_4>
    <HBOND_ACCEPTOR>3</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>1</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>2</ROTATABLE_BONDS>
    <CMR>91.007000000000005</CMR>
    <MOLECULAR_SOLUBILITY>-3.621</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>23</NUM_ATOMS>
    <TPSA>50.160000000000004</TPSA>
    <HALOGEN_COUNT>0</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>5</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>DNA topoisomerase IV; DNA gyrase</TARGET>
    <GVK_ID>GREPAFLOXACIN HYDROCHLORIDE / 5900565</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>CC1CN(CCN1)c2cc3N(C=C(C(=O)O)C(=O)c3c(C)c2F)C4CC4</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>2.03031240753931</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>-1.09197819817157</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-2.34253676654944</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>.118265753878465</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-1.01872040840566</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>.759555241745292</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>1.4080647907201251</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>-1.1573453298279479</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>2.2246410227771705</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>.20824526947513536</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-.96400004614685619</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>.80018239148767734</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>359.39468000000005</MOLECULAR_WEIGHT>
    <CLOGP>-.40600000000000003</CLOGP>
    <LOGD_PH7_4>-.39</LOGD_PH7_4>
    <HBOND_ACCEPTOR>6</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>2</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>3</ROTATABLE_BONDS>
    <CMR>91.977000000000004</CMR>
    <MOLECULAR_SOLUBILITY>-2.9830000000000001</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>26</NUM_ATOMS>
    <TPSA>72.879999999999995</TPSA>
    <HALOGEN_COUNT>1</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>6</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET></TARGET>
    <GVK_ID>GRISEOFULVIN, MICROCRYSTALLINE / 5900566</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>COC1=CC(=O)CC(C)[C@]12Oc3c(Cl)c(OC)cc(OC)c3C2=O</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>2.72837872273441</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>-1.06951408312876</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>2.1101561496717</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-.426739865987799</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>.285938161266027</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>.451471625160218</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>3.2733620615681556</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>-1.0078810063721106</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>.70239079764436818</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-.34669221189071048</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>.32834860309903358</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>.49664425570580056</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>352.76627000000002</MOLECULAR_WEIGHT>
    <CLOGP>2.4950000000000001</CLOGP>
    <LOGD_PH7_4>2.495</LOGD_PH7_4>
    <HBOND_ACCEPTOR>6</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>0</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>3</ROTATABLE_BONDS>
    <CMR>87.650999999999996</CMR>
    <MOLECULAR_SOLUBILITY>-3.706</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>24</NUM_ATOMS>
    <TPSA>71.060000000000002</TPSA>
    <HALOGEN_COUNT>1</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>6</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET></TARGET>
    <GVK_ID>GUAIFENESIN / 5900567</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>COc1ccccc1OCC(O)CO</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-1.71178442874645</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>1.26983102725895</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>4.43347274263615</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-1.16715550407221</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-1.35489561899418</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>-.272056705199816</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-1.7116045609097628</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>1.1625722644861771</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>-2.6417067465150414</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-1.0306128414138671</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-1.3182951329050141</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>-.25221689245069134</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>198.21576000000002</MOLECULAR_WEIGHT>
    <CLOGP>.747</CLOGP>
    <LOGD_PH7_4>.747</LOGD_PH7_4>
    <HBOND_ACCEPTOR>4</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>2</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>5</ROTATABLE_BONDS>
    <CMR>51.239000000000004</CMR>
    <MOLECULAR_SOLUBILITY>-1.2690000000000001</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>14</NUM_ATOMS>
    <TPSA>58.920000000000002</TPSA>
    <HALOGEN_COUNT>0</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>4</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Alpha-2 adrenergic receptor</TARGET>
    <GVK_ID>GUANABENZ ACETATE / 5900568</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>NC(=N)N\N=C/c1c(Cl)cccc1Cl</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-1.19812940371407</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>-1.5632542680733</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-1.52284402802147</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-1.2197733702795</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-.113641793179852</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>1.61931203165802</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-1.6807432374936122</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>-1.6828161012648106</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>-.56242755371529851</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-1.0892600773128822</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-.045269752440845329</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>1.6870686678426492</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>231.08192000000003</MOLECULAR_WEIGHT>
    <CLOGP>2.1920000000000002</CLOGP>
    <LOGD_PH7_4>2.093</LOGD_PH7_4>
    <HBOND_ACCEPTOR>2</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>3</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>3</ROTATABLE_BONDS>
    <CMR>57.914999999999999</CMR>
    <MOLECULAR_SOLUBILITY>-3.1219999999999999</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>14</NUM_ATOMS>
    <TPSA>74.260000000000005</TPSA>
    <HALOGEN_COUNT>2</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>4</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Adrenergic receptor</TARGET>
    <GVK_ID>GUANADREL SULFATE / 5900569</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>NC(=N)NCC1COC2(CCCCC2)O1</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>.964032803406048</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>.128989992161107</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-1.81843456606598</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-1.00660664277383</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-1.71247839819916</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>-.154504659120461</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>1.2086013508591267</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>.42164900733397814</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>-1.7296282919489256</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-.87040242752250896</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-1.6567682750447337</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>-.15032390996719674</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>213.27676000000002</MOLECULAR_WEIGHT>
    <CLOGP>.29399999999999998</CLOGP>
    <LOGD_PH7_4>.19</LOGD_PH7_4>
    <HBOND_ACCEPTOR>3</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>3</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>3</ROTATABLE_BONDS>
    <CMR>56.294000000000004</CMR>
    <MOLECULAR_SOLUBILITY>-.84999999999999998</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>15</NUM_ATOMS>
    <TPSA>80.359999999999999</TPSA>
    <HALOGEN_COUNT>0</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>5</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Adrenergic receptor</TARGET>
    <GVK_ID>GUANETHIDINE MONOSULFATE / 5900570</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>NC(=N)NCCN1CCCCCCC1</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-.894107978075467</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>.00560755431731275</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-1.99543058635223</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-1.18293704400036</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-1.48905709839819</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>-.211318310443291</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-1.1086507908385215</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>.41739451952383766</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>-1.1676757816511718</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-1.0403089324765307</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-1.4504046543511258</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>-.20368042226107907</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>198.30848</MOLECULAR_WEIGHT>
    <CLOGP>1.1859999999999999</CLOGP>
    <LOGD_PH7_4>-.384</LOGD_PH7_4>
    <HBOND_ACCEPTOR>2</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>3</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>4</ROTATABLE_BONDS>
    <CMR>59.457999999999998</CMR>
    <MOLECULAR_SOLUBILITY>-1.206</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>14</NUM_ATOMS>
    <TPSA>65.140000000000001</TPSA>
    <HALOGEN_COUNT>0</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>4</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Alpha-2A adrenergic receptor</TARGET>
    <GVK_ID>GUANFACINE / 5900571</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>NC(=N)NC(=O)Cc1c(Cl)cccc1Cl</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-1.4876462141344</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>.169945497846662</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-1.68143937338882</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-1.14326249681592</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-.192705846906546</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>1.63640154280854</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-1.8630522178190967</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>-.4697906103226851</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>-.82663895011143729</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-1.0163917666689275</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-.12428952541064267</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>1.7041601059007783</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>246.09326000000001</MOLECULAR_WEIGHT>
    <CLOGP>2.0300000000000002</CLOGP>
    <LOGD_PH7_4>1.927</LOGD_PH7_4>
    <HBOND_ACCEPTOR>2</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>3</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>3</ROTATABLE_BONDS>
    <CMR>59.097000000000001</CMR>
    <MOLECULAR_SOLUBILITY>-2.9250000000000003</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>15</NUM_ATOMS>
    <TPSA>78.969999999999999</TPSA>
    <HALOGEN_COUNT>2</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>4</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET></TARGET>
    <GVK_ID>GUANIDINE HYDROCHLORIDE / 5900572</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>NC(=N)N</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>.302492612629381</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>-1.60342051412171</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-1.99143099151835</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-2.31499453465461</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>-2.94770994948227</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>.0890504122533877</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-.21916080851262376</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>-1.4922979657841218</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>-2.3348319435622078</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-2.0812729265676473</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>-2.867935188296789</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>.092853092183534602</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>59.070500000000003</MOLECULAR_WEIGHT>
    <CLOGP>-.98799999999999999</CLOGP>
    <LOGD_PH7_4>-1.091</LOGD_PH7_4>
    <HBOND_ACCEPTOR>1</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>3</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>0</ROTATABLE_BONDS>
    <CMR>15.199</CMR>
    <MOLECULAR_SOLUBILITY>1.1260000000000001</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>4</NUM_ATOMS>
    <TPSA>75.890000000000001</TPSA>
    <HALOGEN_COUNT>0</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>3</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Dopamine receptor D2</TARGET>
    <GVK_ID>CLEBOPRIDE / 5902495</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>COc1cc(N)c(Cl)cc1C(=O)NC2CCN(Cc3ccccc3)CC2</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-2.83174127816804</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>2.05255464681259</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-.222455530714281</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>.0100237217395039</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>.42117558986491</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>.481974442527074</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-2.6878621397876774</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>1.3136709817993673</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>.74584563766673417</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>.073884294959019658</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>.4441149962730192</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>.51821196585242657</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>373.87646000000001</MOLECULAR_WEIGHT>
    <CLOGP>2.633</CLOGP>
    <LOGD_PH7_4>1.073</LOGD_PH7_4>
    <HBOND_ACCEPTOR>4</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>2</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>5</ROTATABLE_BONDS>
    <CMR>105.56700000000001</CMR>
    <MOLECULAR_SOLUBILITY>-4.9969999999999999</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>26</NUM_ATOMS>
    <TPSA>67.590000000000003</TPSA>
    <HALOGEN_COUNT>1</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>5</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Dopamine receptor D2</TARGET>
    <GVK_ID>HALOPERIDOL / 5900577</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>OC1(CCN(CCCC(=O)c2ccc(F)cc2)CC1)c3ccc(Cl)cc3</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>.0429716203914927</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>-.815868404656907</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>-.179703813508367</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>-.53033213240516</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>1.60041871076507</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>1.25268125823895</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>.37468489683035805</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>-2.0868395660424506</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>1.4779218243289867</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>-.46408232291655049</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>1.6067798826199671</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>1.3329487251888328</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>375.86422000000005</MOLECULAR_WEIGHT>
    <CLOGP>3.887</CLOGP>
    <LOGD_PH7_4>3.371</LOGD_PH7_4>
    <HBOND_ACCEPTOR>3</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>1</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>6</ROTATABLE_BONDS>
    <CMR>102.59100000000001</CMR>
    <MOLECULAR_SOLUBILITY>-5.7000000000000002</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>26</NUM_ATOMS>
    <TPSA>40.539999999999999</TPSA>
    <HALOGEN_COUNT>2</HALOGEN_COUNT>
    <NITROGEN_OXYGEN_COUNT>3</NITROGEN_OXYGEN_COUNT>
    <CREATED_USER>Denny</CREATED_USER>
    <CREATED_DATE>05-NOV-09</CREATED_DATE>
    <MODIFIED_USER>MSS</MODIFIED_USER>
    <MODIFIED_DATE>05-NOV-09</MODIFIED_DATE>
  </DATA_RECORD>
  <DATA_RECORD>
    <TARGET>Dopamine receptor D2</TARGET>
    <GVK_ID>HALOPERIDOL DECANOATE / 5900578</GVK_ID>
    <STRUCTURE_ID>10000000</STRUCTURE_ID>
    <VAL_SMILES>CCCCCCCCCC(=O)OC1(CCN(CCCC(=O)c2ccc(F)cc2)CC1)c3ccc(Cl)cc3</VAL_SMILES>
    <ORAL>Y</ORAL>
    <CNS>N</CNS>
    <ORAL_CHEM_PC1>-.596563280840512</ORAL_CHEM_PC1>
    <ORAL_CHEM_PC2>.269723899497905</ORAL_CHEM_PC2>
    <ORAL_CHEM_PC3>.934192659627017</ORAL_CHEM_PC3>
    <ORAL_PHYSPROP_PC1>.839600267628842</ORAL_PHYSPROP_PC1>
    <ORAL_PHYSPROP_PC2>4.70120979020415</ORAL_PHYSPROP_PC2>
    <ORAL_PHYSPROP_PC3>.573333035887103</ORAL_PHYSPROP_PC3>
    <CNS_CHEM_PC1></CNS_CHEM_PC1>
    <CNS_CHEM_PC2></CNS_CHEM_PC2>
    <CNS_CHEM_PC3></CNS_CHEM_PC3>
    <CNS_PHYSPROP_PC1></CNS_PHYSPROP_PC1>
    <CNS_PHYSPROP_PC2></CNS_PHYSPROP_PC2>
    <CNS_PHYSPROP_PC3></CNS_PHYSPROP_PC3>
    <ALL_CHEM_PC1>-.18482955094541378</ALL_CHEM_PC1>
    <ALL_CHEM_PC2>-1.5952076042484895</ALL_CHEM_PC2>
    <ALL_CHEM_PC3>.97991392396591648</ALL_CHEM_PC3>
    <ALL_PHYSPROP_PC1>.74915642194021403</ALL_PHYSPROP_PC1>
    <ALL_PHYSPROP_PC2>4.6265510497316393</ALL_PHYSPROP_PC2>
    <ALL_PHYSPROP_PC3>.67789949724861398</ALL_PHYSPROP_PC3>
    <MOLECULAR_WEIGHT>530.11354000000006</MOLECULAR_WEIGHT>
    <CLOGP>8.1270000000000007</CLOGP>
    <LOGD_PH7_4>7.679</LOGD_PH7_4>
    <HBOND_ACCEPTOR>4</HBOND_ACCEPTOR>
    <HBOND_DONOR_HYDROGEN>0</HBOND_DONOR_HYDROGEN>
    <ROTATABLE_BONDS>16</ROTATABLE_BONDS>
    <CMR>148.57599999999999</CMR>
    <MOLECULAR_SOLUBILITY>-10.01</MOLECULAR_SOLUBILITY>
    <NUM_ATOMS>37</NUM_ATOMS>
    <TPSA>46.609999999999999</TPSA>